### ISSUE TITLE
Transpose function does not work?

### ISSUE THREAD

**Issue by simgust** [kmille/freetar#7]
Loving Freetar, but the transpose function does not seem to work for me. Clicking + or - does nothing. Tested with Chromium browser and Safari on Mac.

https://github.com/kmille/freetar/assets/6162667/b8673ef6-c18e-4cf7-88ba-6b1881a7c185

**Comment by bmacho** [comment]
(not the creator) Those buttons are changing the scroll speed. There is no transpose functionality yet.

**Comment by kmille** [comment]
Hey,
yea we are working on it to integrate it.

**Comment by kmille** [comment]
Fixed in #6 [2e961e9](https://github.com/kmille/freetar/commit/2e961e97be6925e810cc01cb6049902c8790fa79)
